### ISSUE TITLE
exFAT

### ISSUE THREAD

**Issue by teerasak** [captaincookie200/treble_yaap#4]
please support exFAT sd-card.

**Comment by realahnet** [comment]
> please support exFAT sd-card.

i have already included the patch for that. does it not work? Oh i know what happened. i may have broken the patch. i'll try to fix in next build

**Comment by Neucher** [comment]
same issue exfat not detected

**Comment by realahnet** [comment]
> same issue exfat not detected

due to qpr3 rebasing i had to. I usually replace the exfat patch with andy yann's patch as it works and the stock trebledroid one does bot. i forgot to do that after rebasing And because of that its broken. i am currently having issues with my build machine. when i can i'll push out a new build to address this issue as well as other issues. Sorry for the inconvenience

**Comment by Neucher** [comment]
no issue previous build works just fine 👍

**Comment by realahnet** [comment]
> please support exFAT sd-card.



> no issue previous build works just fine +1

please check the latest build and report back to see if the exfat problem is fixed
