### ISSUE TITLE
Can I get Magisk to flash my system.img for up to date Magisk root?

### ISSUE THREAD

**Issue by StupidRepo** [captaincookie200/treble_yaap#9]
Basically, if I download a system.img to my phone and get Magisk to update root on that image, can I just dirty flash it to have up-to-date Magisk root? Just want to know before I (potentially) corrupt something 😭

**Comment by realahnet** [comment]
> Basically, if I download a system.img to my phone and get Magisk to update root on that image, can I just dirty flash it to have up-to-date Magisk root? Just want to know before I (potentially) corrupt something 😭

system image has nothing to do with magisk. you only patch your boot.img which survives gsi updates as it is left untouched

**Comment by StupidRepo** [comment]
Ah ok. How do I get the boot.img of latest GSI build then?

**Comment by realahnet** [comment]
> Ah ok. How do I get the boot.img of latest GSI build then?

oh my god 😭

Generic **SYSTEM** image has nothing to do with any other partitions other than system image partition. rest of your partitions are left untouched and the Generic **SYSTEM** image uses your stock stuff from there. There is no boot.img, vendor.img etc. shipped with Generic **SYSTEM** image. 

For rooting you only patch your boot.img.and then flash the modified boot to your boot partition. It would survive even if you switched gsis since your not touching boot at all. i hope you understand

**Comment by StupidRepo** [comment]
Ohhhh! OK. Sorry, I understand now.
